"""Does the patient-graph model's advantage over Cox concentrate in patients
with thin pre-index medical histories -- the theoretically correct place to
expect a patient-to-patient message-passing model to help (borrowing signal
from similar patients when a patient's own record is sparse)?

Patients are split into "thin" (below-median pre-index fact count) and
"rich" (at or above) groups. The threshold is computed from TRAINING
patients only (same discipline as every other train-only statistic in this
project, e.g. the fairness age-tertile cutpoints) and applied to the test
set. Within each group, AUROC is computed for Cox and the patient-graph
model, and the patient-graph model's margin over Cox is compared between
the two groups.

Replicated across all 5 seeds -- not just seed 42 -- the same bar every
other claim in this project had to clear before being called robust. Per
cell (cause x horizon), a cell counts as "confirmed" if the thin-history
margin is larger than the rich-history margin in at least 4 of 5
independently-trained seeds (matching delong_robustness_audit.py's
convention), avoiding pseudo-replication from treating each seed as an
independent data point within a cell.

No retraining for Cox (reads baselines_survival/predictions_test.csv, seed-
invariant since CoxnetSurvivalAnalysis has no meaningful random_state).
Patient-graph model predictions are regenerated by pure inference from all
5 already-trained checkpoints.

Caveat, stated up front: splitting an already-small test set in half
sharply reduces the positive-case count per cell (as few as 8-20 per
subgroup for the rarer diseases) -- treat per-cell margins as suggestive,
not as results that should be expected to clear a strict significance bar
on their own; the cross-cell pattern is the more trustworthy signal.

Output: tkg_output/stats/cold_start_stratification.csv (per seed, per cell)
        tkg_output/stats/cold_start_stratification_summary.csv (per cell, across seeds)
"""
import os

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score
from scipy import stats as scipy_stats

from src.config import OUTPUT_DIR, read_events_table
from src.baselines_survival import CAUSES, HORIZON_DAYS
from src.evaluate_stats import _labels_for

STATS_DIR = os.path.join(OUTPUT_DIR, "stats")
SEEDS = [42, 43, 44, 45, 46]


def _pg_dir(seed: int) -> str:
    return "patient_gnn_survival" if seed == 42 else f"patient_gnn_survival_seed{seed}"


def _load_patient_graph_probs_all_seeds() -> pd.DataFrame:
    """Pure inference from each seed's already-trained checkpoint -- no
    retraining. The graph/splits are seed-independent (only the trained
    weights differ), so the graph data is built once and reused."""
    from src.tgn_survival import CAUSES as C, NUM_CAUSES, NUM_TIME_BINS, _make_time_bins
    from src.ablations.patient_graph_gnn import PatientConceptGNN, _prepare_patient_graph_data

    print("Building patient-graph data (shared across all 5 seed checkpoints)...")
    d = _prepare_patient_graph_data()
    labels_df = d["labels_df"]
    train_sids = d["splits"]["train"]
    train_durations = labels_df.loc[
        labels_df["subject_id"].isin(train_sids), "time_to_event_days"
    ].to_numpy(dtype=np.float32)
    time_edges = _make_time_bins(train_durations, NUM_TIME_BINS)
    test_sids = d["splits"]["test"]
    test_pos = np.array([d["pid_to_pos"][s] for s in test_sids])
    bin_idx_by_h = {h: int(np.searchsorted(time_edges, h, side="right") - 1) for h in HORIZON_DAYS}

    merged = pd.DataFrame({"subject_id": test_sids})
    for seed in SEEDS:
        print(f"  seed {seed}...")
        ckpt = os.path.join(OUTPUT_DIR, _pg_dir(seed), "best_model.pt")
        model = PatientConceptGNN(
            n_concepts=d["n_concepts"], n_patients=d["n_patients"], n_static=d["n_static"],
            n_relations=d["n_relations"], edge_index=d["edge_index"], edge_type=d["edge_type"],
            n_classes=NUM_CAUSES * NUM_TIME_BINS,
        )
        state = torch.load(ckpt, map_location="cpu")
        model.load_state_dict(state["state_dict"])
        model.eval()
        with torch.no_grad():
            logits_flat = model(d["static_arr"])
            logits = logits_flat.view(-1, NUM_CAUSES, NUM_TIME_BINS)
            probs = F.softmax(logits.reshape(logits.size(0), -1), dim=-1).view_as(logits)
            cif = torch.cumsum(probs, dim=-1).numpy()
        cif_test = cif[test_pos]
        for i, cause in enumerate(C):
            for h in HORIZON_DAYS:
                b = max(0, min(bin_idx_by_h[h], cif_test.shape[-1] - 1))
                merged[f"pg_cif_{cause}_at_{h}d_seed{seed}"] = cif_test[:, i, b]
    return merged


def run() -> None:
    os.makedirs(STATS_DIR, exist_ok=True)
    print("Computing pre-index fact counts per patient...")
    events = read_events_table()
    fact_count = events.groupby("subject_id").size().rename("n_facts")

    labels = pd.read_csv(os.path.join(OUTPUT_DIR, "modeling", "labels.csv"))
    train_ids = labels.loc[labels["split"] == "train", "subject_id"]
    train_counts = fact_count.reindex(train_ids).fillna(0)
    threshold = float(train_counts.median())
    print(f"  train-only median pre-index fact count: {threshold:.0f}")

    test_labels = labels[labels["split"] == "test"][["subject_id", "endpoint_type", "time_to_event_days"]].copy()
    test_labels["n_facts"] = fact_count.reindex(test_labels["subject_id"]).fillna(0).to_numpy()
    test_labels["history_group"] = np.where(test_labels["n_facts"] < threshold, "thin", "rich")
    print(f"  test set: {(test_labels.history_group == 'thin').sum()} thin, "
          f"{(test_labels.history_group == 'rich').sum()} rich")

    cox_preds = pd.read_csv(os.path.join(OUTPUT_DIR, "baselines_survival", "predictions_test.csv"))
    pg_preds = _load_patient_graph_probs_all_seeds()

    df = test_labels.merge(cox_preds, on="subject_id").merge(pg_preds, on="subject_id")
    evts = df["endpoint_type"].to_numpy()
    durs = df["time_to_event_days"].to_numpy(dtype=float)

    rows = []
    print(f"\n=== Patient-graph margin over Cox, by history group, all {len(SEEDS)} seeds ===\n")
    for cause in CAUSES:
        for h in HORIZON_DAYS:
            y_all, mask_all = _labels_for(cause, h, evts, durs)
            if y_all.sum() == 0 or y_all.sum() == len(y_all):
                continue
            for seed in SEEDS:
                for group in ["thin", "rich"]:
                    grp_mask = (df["history_group"] == group).to_numpy() & mask_all
                    y = ((evts[grp_mask] == cause) & (durs[grp_mask] <= h)).astype(int)
                    n_pos, n = int(y.sum()), int(len(y))
                    if n_pos < 3 or n_pos == n:
                        rows.append(dict(cause=cause, horizon_days=h, seed=seed, group=group,
                                          n=n, n_pos=n_pos, cox_auc=np.nan, pg_auc=np.nan, pg_minus_cox=np.nan))
                        continue
                    cox_s = df.loc[grp_mask, f"cox_risk_{cause}"].to_numpy(float)
                    pg_s = df.loc[grp_mask, f"pg_cif_{cause}_at_{h}d_seed{seed}"].to_numpy(float)
                    cox_auc = roc_auc_score(y, cox_s)
                    pg_auc = roc_auc_score(y, pg_s)
                    rows.append(dict(cause=cause, horizon_days=h, seed=seed, group=group, n=n, n_pos=n_pos,
                                      cox_auc=round(cox_auc, 4), pg_auc=round(pg_auc, 4),
                                      pg_minus_cox=round(pg_auc - cox_auc, 4)))

    result = pd.DataFrame(rows)
    out_path = os.path.join(STATS_DIR, "cold_start_stratification.csv")
    result.to_csv(out_path, index=False)

    valid = result.dropna(subset=["pg_minus_cox"])
    pivot = valid.pivot_table(index=["cause", "horizon_days", "seed"], columns="group", values="pg_minus_cox")
    pivot = pivot.dropna()
    pivot["thin_larger"] = pivot["thin"] > pivot["rich"]

    cell_summary = pivot.groupby(["cause", "horizon_days"]).agg(
        n_seeds=("thin_larger", "size"), n_seeds_thin_larger=("thin_larger", "sum"),
        mean_thin_margin=("thin", "mean"), mean_rich_margin=("rich", "mean"),
    ).reset_index()
    cell_summary["cell_confirmed"] = cell_summary["n_seeds_thin_larger"] >= 4

    n_confirmed = int(cell_summary["cell_confirmed"].sum())
    n_cells = len(cell_summary)
    sign_p = scipy_stats.binomtest(n_confirmed, n_cells, 0.5, alternative="two-sided").pvalue
    cell_summary["sign_test_p"] = round(sign_p, 4)
    cell_summary["n_cells_confirmed"] = n_confirmed
    cell_summary["n_cells"] = n_cells
    cell_summary.to_csv(os.path.join(STATS_DIR, "cold_start_stratification_summary.csv"), index=False)

    print(f"\n=== SUMMARY (per cell, across all {len(SEEDS)} seeds) ===")
    print(cell_summary[["cause", "horizon_days", "n_seeds_thin_larger", "mean_thin_margin",
                         "mean_rich_margin", "cell_confirmed"]].round(4).to_string(index=False))
    print(f"\n{n_confirmed} of {n_cells} cells confirmed (thin-history margin larger in >=4/5 seeds); "
          f"sign test across cells p={sign_p:.4f}")
    print(f"\nSaved:\n  {out_path}\n  {os.path.join(STATS_DIR, 'cold_start_stratification_summary.csv')}")


if __name__ == "__main__":
    run()
