"""AUPRC + 95% bootstrap CIs for the three models featured in the main
results comparison: Cox, XGBoost, and the patient-graph GNN (5-seed).

AUROC already has bootstrap CIs for these models (see
tuned_models_significance.py). AUPRC is the threshold-free complement that
is actually informative given how rare these events are (0.4%-5.2% test-set
prevalence) -- it is what best-F1's low scores are a symptom of (see
threshold_metrics.py / *_recall_f1_best), so putting a number and a CI on it
directly, rather than only on the threshold-based F1, closes that gap.

Reuses already-saved artifacts, no retraining:
  - Cox / XGBoost per-patient test risk scores from
    tkg_output/baselines_survival/predictions_test.csv.
  - patient-graph GNN per-patient test CIF probabilities, regenerated by
    inference only from each of the 5 already-trained checkpoints
    (patient_gnn_survival[_seed*]/best_model.pt) -- same models used
    throughout the main results (patient_gnn_multi_seed_comparison.csv).

Output: tkg_output/stats/tuned_models_auprc_ci.csv
"""
import os

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from sklearn.metrics import average_precision_score

from src.config import OUTPUT_DIR
from src.baselines_survival import CAUSES, HORIZON_DAYS
from src.evaluate_stats import _labels_for, _bootstrap_ci

STATS_DIR = os.path.join(OUTPUT_DIR, "stats")
N_BOOT = 2000
SEEDS = [42, 43, 44, 45, 46]


def _pg_model_dir(seed: int) -> str:
    return os.path.join(OUTPUT_DIR, "patient_gnn_survival" if seed == 42
                         else f"patient_gnn_survival_seed{seed}")


def _load_patient_graph_probs(seed: int) -> pd.DataFrame:
    """Re-run inference from the saved checkpoint for `seed` (no retraining) --
    same approach as tuned_models_significance.py's seed-42-only version,
    generalized to any of the 5 already-trained seeds."""
    from src.tgn_survival import CAUSES as C, NUM_CAUSES, NUM_TIME_BINS, _make_time_bins
    from src.ablations.patient_graph_gnn import PatientConceptGNN, _prepare_patient_graph_data

    d = _prepare_patient_graph_data()
    labels_df = d["labels_df"]
    train_sids = d["splits"]["train"]
    train_durations = labels_df.loc[
        labels_df["subject_id"].isin(train_sids), "time_to_event_days"
    ].to_numpy(dtype=np.float32)
    time_edges = _make_time_bins(train_durations, NUM_TIME_BINS)

    model = PatientConceptGNN(
        n_concepts=d["n_concepts"], n_patients=d["n_patients"], n_static=d["n_static"],
        n_relations=d["n_relations"], edge_index=d["edge_index"], edge_type=d["edge_type"],
        n_classes=NUM_CAUSES * NUM_TIME_BINS,
    )
    state = torch.load(os.path.join(_pg_model_dir(seed), "best_model.pt"), map_location="cpu")
    model.load_state_dict(state["state_dict"])
    model.eval()
    with torch.no_grad():
        logits_flat = model(d["static_arr"])
        logits = logits_flat.view(-1, NUM_CAUSES, NUM_TIME_BINS)
        probs = F.softmax(logits.reshape(logits.size(0), -1), dim=-1).view_as(logits)
        cif = torch.cumsum(probs, dim=-1).numpy()

    test_sids = d["splits"]["test"]
    test_pos = np.array([d["pid_to_pos"][s] for s in test_sids])
    cif_test = cif[test_pos]

    bin_idx_by_h = {h: int(np.searchsorted(time_edges, h, side="right") - 1) for h in HORIZON_DAYS}

    out = pd.DataFrame({"subject_id": test_sids})
    for i, cause in enumerate(C):
        for h in HORIZON_DAYS:
            b = max(0, min(bin_idx_by_h[h], cif_test.shape[-1] - 1))
            out[f"pg_cif_{cause}_at_{h}d"] = cif_test[:, i, b]
    return out


def run() -> None:
    os.makedirs(STATS_DIR, exist_ok=True)

    print("Loading Cox / XGBoost per-patient predictions (already saved)...")
    tuned_preds = pd.read_csv(os.path.join(OUTPUT_DIR, "baselines_survival", "predictions_test.csv"))

    labels_all = pd.read_csv(os.path.join(OUTPUT_DIR, "modeling", "labels.csv"))
    test_labels = labels_all[labels_all.split == "test"][
        ["subject_id", "endpoint_type", "time_to_event_days"]]

    print("Regenerating patient-graph GNN test predictions from all 5 saved checkpoints "
          "(inference only, no retraining)...")
    pg_preds_by_seed = {}
    for seed in SEEDS:
        print(f"  seed {seed}...")
        pg_preds_by_seed[seed] = _load_patient_graph_probs(seed)

    df = test_labels.merge(tuned_preds, on="subject_id")
    for seed in SEEDS:
        renamed = pg_preds_by_seed[seed].rename(
            columns={c: f"{c}_seed{seed}" for c in pg_preds_by_seed[seed].columns if c != "subject_id"})
        df = df.merge(renamed, on="subject_id")

    evts = df["endpoint_type"].to_numpy()
    durs = df["time_to_event_days"].to_numpy(dtype=float)

    rows = []
    print("\n=== AUPRC with 95% bootstrap CI ===\n")
    for cause in CAUSES:
        for h in HORIZON_DAYS:
            y, mask = _labels_for(cause, h, evts, durs)
            n_pos, n = int(y.sum()), int(len(y))
            if n_pos == 0 or n_pos == n:
                continue

            # -- Cox --
            s_cox = df.loc[mask, f"cox_risk_{cause}"].to_numpy(float)
            auprc_cox = average_precision_score(y, s_cox)
            lo_cox, hi_cox = _bootstrap_ci(y, s_cox, average_precision_score, n_boot=N_BOOT)

            # -- XGBoost --
            s_xgb = df.loc[mask, f"xgb_surv_risk_{cause}"].to_numpy(float)
            auprc_xgb = average_precision_score(y, s_xgb)
            lo_xgb, hi_xgb = _bootstrap_ci(y, s_xgb, average_precision_score, n_boot=N_BOOT)

            rows.append(dict(cause=cause, horizon_days=h, model="cox",
                              auprc=round(auprc_cox, 4), auprc_ci_low=round(lo_cox, 4),
                              auprc_ci_high=round(hi_cox, 4), n_pos=n_pos, n=n))
            rows.append(dict(cause=cause, horizon_days=h, model="xgb_surv",
                              auprc=round(auprc_xgb, 4), auprc_ci_low=round(lo_xgb, 4),
                              auprc_ci_high=round(hi_xgb, 4), n_pos=n_pos, n=n))

            # -- patient-graph GNN, 5 seeds: per-seed AUPRC, mean/std across
            #    seeds, and a bootstrap CI computed on the seed-42 run
            #    (same "seed42 for CI, 5-seed for distribution" convention
            #    tuned_models_significance.py already uses for AUROC) --
            pg_auprcs = []
            for seed in SEEDS:
                s_pg = df.loc[mask, f"pg_cif_{cause}_at_{h}d_seed{seed}"].to_numpy(float)
                pg_auprcs.append(average_precision_score(y, s_pg))
            pg_auprcs = np.array(pg_auprcs)
            s_pg42 = df.loc[mask, f"pg_cif_{cause}_at_{h}d_seed42"].to_numpy(float)
            lo_pg, hi_pg = _bootstrap_ci(y, s_pg42, average_precision_score, n_boot=N_BOOT)

            rows.append(dict(cause=cause, horizon_days=h, model="patient_graph_5seed_mean",
                              auprc=round(float(pg_auprcs.mean()), 4),
                              auprc_std=round(float(pg_auprcs.std()), 4),
                              auprc_ci_low=round(lo_pg, 4), auprc_ci_high=round(hi_pg, 4),
                              n_pos=n_pos, n=n))

            print(f"  {cause:8s} {h}d  cox={auprc_cox:.4f}[{lo_cox:.4f},{hi_cox:.4f}]  "
                  f"xgb={auprc_xgb:.4f}[{lo_xgb:.4f},{hi_xgb:.4f}]  "
                  f"pg={pg_auprcs.mean():.4f}±{pg_auprcs.std():.4f}"
                  f"[{lo_pg:.4f},{hi_pg:.4f}] (seed42 CI)  n_pos={n_pos}/{n}")

    result = pd.DataFrame(rows)
    out_path = os.path.join(STATS_DIR, "tuned_models_auprc_ci.csv")
    result.to_csv(out_path, index=False)

    print(f"\n=== Overall mean AUPRC across all 15 disease/horizon cells ===")
    print(result.groupby("model")["auprc"].mean().round(4))
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    run()
