"""Significance testing for Cox vs. XGBoost and Cox vs. the patient-graph
model, using the same statistical machinery already used for every other
comparison in this study (bootstrap 95% CIs, paired DeLong tests accounting
for correlation on shared test patients, and the one-sample-t-test-against-
a-fixed-Cox-value protocol from multi_seed_summary.py).

No retraining: Cox and XGBoost predictions come directly from
baselines_survival/predictions_test.csv. Patient-graph model predictions
are regenerated by pure inference from the already-trained seed-42
checkpoint (patient_graph_gnn.py never saves per-patient predictions).

Output: tkg_output/stats/tuned_models_significance.csv
"""
import os

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from scipy import stats
from sklearn.metrics import roc_auc_score

from src.config import OUTPUT_DIR, SEED
from src.baselines_survival import CAUSES, HORIZON_DAYS
from src.evaluate_stats import delong_test, _labels_for, _bootstrap_ci

STATS_DIR = os.path.join(OUTPUT_DIR, "stats")
N_BOOT = 2000


def _load_patient_graph_probs_seed42():
    """Re-run inference from the saved seed-42 checkpoint (no retraining) --
    same approach as calibration_and_fairness.py, since patient_graph_gnn.py
    never saved per-patient predictions."""
    from src.tgn_survival import CAUSES as C, NUM_CAUSES, NUM_TIME_BINS, _make_time_bins
    from src.ablations.patient_graph_gnn import PatientConceptGNN, _prepare_patient_graph_data, MODEL_DIR

    d = _prepare_patient_graph_data()
    labels_df = d["labels_df"]
    train_sids = d["splits"]["train"]
    train_durations = labels_df.loc[
        labels_df["subject_id"].isin(train_sids), "time_to_event_days"
    ].to_numpy(dtype=np.float32)
    time_edges = _make_time_bins(train_durations, NUM_TIME_BINS)

    model = PatientConceptGNN(
        n_concepts=d["n_concepts"], n_patients=d["n_patients"], n_static=d["n_static"],
        n_relations=d["n_relations"], edge_index=d["edge_index"], edge_type=d["edge_type"],
        n_classes=NUM_CAUSES * NUM_TIME_BINS,
    )
    state = torch.load(os.path.join(MODEL_DIR, "best_model.pt"), map_location="cpu")
    model.load_state_dict(state["state_dict"])
    model.eval()
    with torch.no_grad():
        logits_flat = model(d["static_arr"])
        logits = logits_flat.view(-1, NUM_CAUSES, NUM_TIME_BINS)
        probs = F.softmax(logits.reshape(logits.size(0), -1), dim=-1).view_as(logits)
        cif = torch.cumsum(probs, dim=-1).numpy()

    test_sids = d["splits"]["test"]
    test_pos = np.array([d["pid_to_pos"][s] for s in test_sids])
    cif_test = cif[test_pos]

    bin_idx_by_h = {}
    for h in HORIZON_DAYS:
        bin_idx_by_h[h] = int(np.searchsorted(time_edges, h, side="right") - 1)

    out = pd.DataFrame({"subject_id": test_sids})
    for i, cause in enumerate(C):
        for h in HORIZON_DAYS:
            b = max(0, min(bin_idx_by_h[h], cif_test.shape[-1] - 1))
            out[f"pg_cif_{cause}_at_{h}d"] = cif_test[:, i, b]
    return out


def run() -> None:
    os.makedirs(STATS_DIR, exist_ok=True)
    baseline_preds = pd.read_csv(os.path.join(OUTPUT_DIR, "baselines_survival", "predictions_test.csv"))
    pg_preds = _load_patient_graph_probs_seed42()

    labels_all = pd.read_csv(os.path.join(OUTPUT_DIR, "modeling", "labels.csv"))
    test_labels = labels_all[labels_all.split == "test"][["subject_id", "endpoint_type", "time_to_event_days"]]

    df = test_labels.merge(pg_preds, on="subject_id").merge(baseline_preds, on="subject_id")
    evts = df["endpoint_type"].to_numpy()
    durs = df["time_to_event_days"].to_numpy(dtype=float)

    pg_multiseed = pd.read_csv(os.path.join(STATS_DIR, "patient_gnn_multi_seed_comparison.csv"))

    rows = []
    print("\n=== Bootstrap CI (Cox) + DeLong tests + seed-distribution t-test ===\n")
    for cause in CAUSES:
        for h in HORIZON_DAYS:
            y, mask = _labels_for(cause, h, evts, durs)
            cox_s = df.loc[mask, f"cox_risk_{cause}"].to_numpy(float)
            xgb_s = df.loc[mask, f"xgb_surv_risk_{cause}"].to_numpy(float)
            pg_s = df.loc[mask, f"pg_cif_{cause}_at_{h}d"].to_numpy(float)

            if y.sum() == 0 or y.sum() == len(y):
                continue

            ci_lo, ci_hi = _bootstrap_ci(y, cox_s, roc_auc_score, n_boot=N_BOOT, seed=SEED)
            cox_auc = roc_auc_score(y, cox_s)

            _, _, p_vs_xgb = delong_test(y, cox_s, xgb_s)
            _, _, p_vs_pg_seed42 = delong_test(y, cox_s, pg_s)

            # One-sample t-test: patient-graph 5-seed distribution vs the
            # fixed Cox value -- exact protocol of multi_seed_summary.py
            pg_row = pg_multiseed[(pg_multiseed.cause == cause) & (pg_multiseed.horizon == h)]
            pg_mean = float(pg_row["pg_mean"].iloc[0])
            pg_std = float(pg_row["pg_std"].iloc[0])
            seed_vals = []
            for s in [42, 43, 44, 45, 46]:
                pg_dir = "patient_gnn_survival" if s == 42 else f"patient_gnn_survival_seed{s}"
                tm = pd.read_csv(os.path.join(OUTPUT_DIR, pg_dir, "test_metrics.csv"))
                v = tm[(tm.cause == cause) & (tm.horizon_days == h)]["auroc"]
                if len(v):
                    seed_vals.append(float(v.iloc[0]))
            seed_vals = np.array(seed_vals)
            if len(seed_vals) >= 2 and np.isfinite(cox_auc):
                _, p_ttest = stats.ttest_1samp(seed_vals, popmean=cox_auc)
            else:
                p_ttest = np.nan

            rows.append(dict(
                cause=cause, horizon_days=h,
                cox_auc=round(cox_auc, 4),
                cox_ci_low=round(ci_lo, 4), cox_ci_high=round(ci_hi, 4),
                xgb_auc=round(roc_auc_score(y, xgb_s), 4),
                delong_p_cox_vs_xgb=round(p_vs_xgb, 4),
                pg_seed42_auc=round(roc_auc_score(y, pg_s), 4),
                delong_p_cox_vs_pg_seed42=round(p_vs_pg_seed42, 4),
                pg_5seed_mean=round(pg_mean, 4), pg_5seed_std=round(pg_std, 4),
                ttest_p_pg5seed_vs_cox=round(p_ttest, 4) if np.isfinite(p_ttest) else np.nan,
            ))
            print(f"  {cause:8s} {h}d  cox={cox_auc:.4f} [{ci_lo:.4f},{ci_hi:.4f}]  "
                  f"vs xgb p={p_vs_xgb:.4f}  vs pg(seed42) p={p_vs_pg_seed42:.4f}  "
                  f"vs pg(5-seed dist) p={p_ttest:.4f}" if np.isfinite(p_ttest) else "")

    result = pd.DataFrame(rows)
    n_tests = len(result)
    alpha_bonf = 0.05 / n_tests
    result["sig_vs_pg_5seed_bonf"] = result["ttest_p_pg5seed_vs_cox"] < alpha_bonf
    result["sig_vs_xgb_bonf"] = result["delong_p_cox_vs_xgb"] < alpha_bonf

    out_path = os.path.join(STATS_DIR, "tuned_models_significance.csv")
    result.to_csv(out_path, index=False)

    print(f"\n=== SUMMARY (Bonferroni alpha={alpha_bonf:.5f} across {n_tests} tests) ===")
    print(result[["cause", "horizon_days", "cox_auc", "pg_5seed_mean",
                   "ttest_p_pg5seed_vs_cox", "sig_vs_pg_5seed_bonf",
                   "xgb_auc", "delong_p_cox_vs_xgb", "sig_vs_xgb_bonf"]].to_string(index=False))
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    run()
